import JSZip from 'jszip';
import type { GCodeFile } from '../types';
import { calculateTotalTime } from './fileProcessor';

function createPrintSeparator(
  printNumber: number,
  totalPrints: number,
  fileName: string,
  copyNumber?: number,
  totalCopies?: number,
): string {
  const lines: string[] = ['', ';========================================'];

  if (
    copyNumber !== undefined &&
    totalCopies !== undefined &&
    totalCopies > 1
  ) {
    lines.push(
      `;===== PRINT ${printNumber} of ${totalPrints}: ${fileName} (Copy ${copyNumber}/${totalCopies}) =====`,
    );
  } else {
    lines.push(
      `;===== PRINT ${printNumber} of ${totalPrints}: ${fileName} =====`,
    );
  }

  lines.push(';========================================', '');

  return lines.join('\n');
}

function createCombinedHeader(
  files: GCodeFile[],
  totalPrints: number,
  totalTime: string | null,
): string {
  const lines: string[] = [
    ';========================================',
    ';===== COMBINED PRINT FILE =====',
    ';========================================',
    ';',
    `; Generated by G-code Combiner`,
    `; Date: ${new Date().toISOString()}`,
    ';',
    `; Total prints in this file: ${totalPrints}`,
  ];

  if (totalTime) {
    lines.push(`; Estimated total time: ${totalTime}`);
  }

  lines.push(';', '; Print order:');

  let printIndex = 1;
  for (const file of files) {
    if (file.copies > 1) {
      for (let copy = 1; copy <= file.copies; copy++) {
        lines.push(
          `;   ${printIndex}. ${file.fileName} (Copy ${copy}/${file.copies})`,
        );
        printIndex++;
      }
    } else {
      lines.push(`;   ${printIndex}. ${file.fileName}`);
      printIndex++;
    }
  }

  lines.push(';', ';========================================', '', '');

  return lines.join('\n');
}

export function combineGCode(files: GCodeFile[]): string {
  // Calculate total number of prints (accounting for copies)
  const totalPrints = files.reduce((sum, file) => sum + file.copies, 0);

  if (totalPrints === 0) {
    throw new Error('No files to combine');
  }

  const totalTime = calculateTotalTime(files);
  const combinedParts: string[] = [];

  // Add header with print information
  combinedParts.push(createCombinedHeader(files, totalPrints, totalTime));

  let currentPrint = 1;

  for (const file of files) {
    for (let copy = 1; copy <= file.copies; copy++) {
      // Add separator before each print
      const separator =
        file.copies > 1
          ? createPrintSeparator(
              currentPrint,
              totalPrints,
              file.fileName,
              copy,
              file.copies,
            )
          : createPrintSeparator(currentPrint, totalPrints, file.fileName);

      combinedParts.push(separator);
      combinedParts.push(file.gcode);

      // Ensure there's a newline at the end of each G-code section
      if (!file.gcode.endsWith('\n')) {
        combinedParts.push('\n');
      }

      currentPrint++;
    }
  }

  return combinedParts.join('');
}

export async function createCombinedZip(
  files: GCodeFile[],
  combinedGCode: string,
): Promise<Blob> {
  // Use the first file as a template
  const templateFile = files[0];
  const templateZip = await JSZip.loadAsync(templateFile.originalZip);

  // Create a new ZIP with the same structure
  const newZip = new JSZip();

  // Copy all files from the template except the G-code
  const allFiles = Object.keys(templateZip.files);

  for (const filePath of allFiles) {
    const file = templateZip.files[filePath];

    if (file.dir) {
      newZip.folder(filePath);
      continue;
    }

    // Skip the original G-code file - we'll add our combined version
    if (filePath.includes('.gcode')) {
      continue;
    }

    // Copy other files as-is
    const content = await file.async('arraybuffer');
    newZip.file(filePath, content);
  }

  // Add the combined G-code
  newZip.file('Metadata/plate_1.gcode', combinedGCode);

  // Generate the ZIP file
  return newZip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
